1. Import Libraries

In [1]:
import numpy as np
import pandas as pd

2. Import Data

In [7]:
df = pd.read_csv("../data/SampleSuperstore.csv")

In [9]:
df.shape[0]

9994

In [10]:
df.shape[1]

13

In [11]:
df.columns.tolist()

['Ship Mode',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Category',
 'Sub-Category',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [12]:
df.dtypes

Ship Mode        object
Segment          object
Country          object
City             object
State            object
Postal Code       int64
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

3. Check Null Values

In [17]:
null_counts = df.isnull().sum()
null_counts

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [19]:
null_report = pd.DataFrame({
    "null_count" : null_counts
})
null_report

              null_count
Ship Mode              0
Segment                0
Country                0
City                   0
State                  0
Postal Code            0
Region                 0
Category               0
Sub-Category           0
Sales                  0
Quantity               0
Discount               0
Profit                 0

4. Remove Duplicates

In [22]:
duplicates = df.duplicated().sum()
print(duplicates)

17

In [23]:
df.drop_duplicates(inplace = True)

In [26]:
df.duplicated().sum()

np.int64(0)

4. Check Wrong Values

In [27]:
df['Sales'].describe()

count     9977.000000
mean       230.148902
std        623.721409
min          0.444000
25%         17.300000
50%         54.816000
75%        209.970000
max      22638.480000
Name: Sales, dtype: float64

In [28]:
df[df['Sales'] < 0]

Empty DataFrame
Columns: [Ship Mode, Segment, Country, City, State, Postal Code, Region, Category, Sub-Category, Sales, Quantity, Discount, Profit]
Index: []

In [30]:
df['Quantity'].describe()

count    9977.000000
mean        3.790719
std         2.226657
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max        14.000000
Name: Quantity, dtype: float64

In [31]:
df[df['Quantity'] <= 0]

Empty DataFrame
Columns: [Ship Mode, Segment, Country, City, State, Postal Code, Region, Category, Sub-Category, Sales, Quantity, Discount, Profit]
Index: []

In [32]:
df['Discount'].describe()

count    9977.000000
mean        0.156278
std         0.206455
min         0.000000
25%         0.000000
50%         0.200000
75%         0.200000
max         0.800000
Name: Discount, dtype: float64

In [33]:
df[(df['Discount'] < 0) | (df['Discount'] > 1)]

Empty DataFrame
Columns: [Ship Mode, Segment, Country, City, State, Postal Code, Region, Category, Sub-Category, Sales, Quantity, Discount, Profit]
Index: []

FEATURE ENGINEERING

1.Profit Margin

In [34]:
df['Profit Margin'] = (df['Profit'] / df['Sales']) * 100

In [44]:
df['Profit Margin'] = df['Profit Margin'].round(2)

In [45]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin,Profit Status,Sales Category
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,Profit,Medium
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,Profit,High
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,Profit,Low
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,Loss,High
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,Profit,Low

2. Profit Category

In [46]:
df["Profit Status"] =  np.where(df['Profit'] >= 0, 'Profit', 'Loss')

In [47]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin,Profit Status,Sales Category
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,Profit,Medium
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,Profit,High
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,Profit,Low
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,Loss,High
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,Profit,Low

3. Sales Category

In [54]:
df['Sales Category'] = pd.cut(df['Sales'], bins = [0,100,500,1000,5000,25000], labels= ['Low','Medium','High','Very High','Premium'])

In [55]:
df[['Sales', 'Sales Category']].head()

      Sales Sales Category
0  261.9600         Medium
1  731.9400           High
2   14.6200            Low
3  957.5775           High
4   22.3680            Low

In [56]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin,Profit Status,Sales Category
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,Profit,Medium
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,Profit,High
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,Profit,Low
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,Loss,High
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,Profit,Low

OUTLIER DETECTION

In [64]:
def check_outliers(column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower_limit) | (df[column] > upper_limit)]

    return outliers, lower_limit, upper_limit

1. Sales Outliers

In [70]:
sales_outliers, sales_low, sales_high = check_outliers('Sales')
print("Sales outliers:", len(sales_outliers))
print("Lower limit:", sales_low)
print("Upper limit:", sales_high)

Sales outliers: 1167
Lower limit: -271.705
Upper limit: 498.975

In [71]:
sales_outliers[['Category','Sub-Category','Sales','Profit']].head(20)

            Category Sub-Category      Sales     Profit
1          Furniture       Chairs   731.9400   219.5820
3          Furniture       Tables   957.5775  -383.0310
7         Technology       Phones   907.1520    90.7152
10         Furniture       Tables  1706.1840    85.3092
11        Technology       Phones   911.4240    68.3568
16   Office Supplies      Storage   665.8800    13.3176
24         Furniture       Tables  1044.6300   240.2649
27         Furniture    Bookcases  3083.4300 -1665.0522
35        Technology       Phones  1097.5440   123.4737
38         Furniture    Bookcases   532.3992   -46.9764
54        Technology       Phones  1029.9500   298.6855
67   Office Supplies          Art  1113.0240   111.3024
72         Furniture       Chairs   831.9360  -114.3912
117        Furniture       Tables   787.5300   165.3813
124        Furniture       Chairs   600.5580    -8.5794
125        Furniture       Tables   617.7000  -407.6820
144  Office Supplies   Appliances   839.4300   218.2518
145  Office Supplies      Storage   671.9300    20.1579
149        Furniture       Chairs  1951.8400   585.5520
159       Technology       Phones   944.9300   236.2325

In [72]:
df['Sales Outlier'] = np.where((df['Sales'] < sales_low) | (df['Sales'] > sales_high),'Yes','No')

In [73]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin,Profit Status,Sales Category,Sales Outlier
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,Profit,Medium,No
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,Profit,High,Yes
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,Profit,Low,No
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,Loss,High,Yes
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,Profit,Low,No

2. Profit Outliers

In [74]:
profit_outliers, profit_low, profit_high = check_outliers('Profit')
print("Profit outliers:", len(profit_outliers))
print("Lower limit:", profit_low)
print('Upper limit:', profit_high)

Profit outliers: 1881
Lower limit: -39.7425
Upper limit: 70.8407

In [75]:
profit_outliers, profit_low, profit_high = check_outliers("Profit")

df["Profit Outlier"] = np.where(
    (df["Profit"] < profit_low) |
    (df["Profit"] > profit_high),
    "Yes",
    "No"
)

In [76]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin,Profit Status,Sales Category,Sales Outlier,Profit Outlier
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,Profit,Medium,No,No
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,Profit,High,Yes,Yes
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,Profit,Low,No,No
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,Loss,High,Yes,Yes
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,Profit,Low,No,No

3. Qunatity Outliers

In [77]:
quantity_outliers, q_low, q_high = check_outliers("Quantity")

print("Quantity outliers:", len(quantity_outliers))

Quantity outliers: 170

In [78]:
quantity_outliers, q_low, q_high = check_outliers("Quantity")

df["Quantity Outlier"] = np.where(
    (df["Quantity"] < q_low) |
    (df["Quantity"] > q_high),
    "Yes",
    "No"
)

In [79]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin,Profit Status,Sales Category,Sales Outlier,Profit Outlier,Quantity Outlier
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,Profit,Medium,No,No,No
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,Profit,High,Yes,Yes,No
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,Profit,Low,No,No,No
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,Loss,High,Yes,Yes,No
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,Profit,Low,No,No,No

FINAL CHECK

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9977 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Ship Mode         9977 non-null   object
 1   Segment           9977 non-null   object
 2   Country           9977 non-null   object
 3   City              9977 non-null   object
 4   State             9977 non-null   object
 5   Postal Code       9977 non-null   int64
 6   Region            9977 non-null   object
 7   Category          9977 non-null   object
 8   Sub-Category      9977 non-null   object
 9   Sales             9977 non-null   float64
 10  Quantity          9977 non-null   int64
 11  Discount          9977 non-null   float64
 12  Profit            9977 non-null   float64
 13  Profit Margin     9977 non-null   float64
 14  Profit Status     9977 non-null   object
 15  Sales Category    9977 non-null   category
 16  Sales Outlier     9977 non-null   object
 17  Profit Outlier    9977 non-null   object
 18  Quantity Outlier  9977 non-null   object
dtypes: category(1), float64(4), int64(2), object(12)
memory usage: 1.5+ MB

In [81]:
df.isnull().sum()

Ship Mode           0
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub-Category        0
Sales               0
Quantity            0
Discount            0
Profit              0
Profit Margin       0
Profit Status       0
Sales Category      0
Sales Outlier       0
Profit Outlier      0
Quantity Outlier    0
dtype: int64

FINAL SAVE

In [82]:
df.to_csv('../data/superstore_clean.csv', index = False)